import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import { roboto_mono } from './styles/fonts';
import QueryProvider from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_mono.className}>
        <nav className="p-2">
          <ul className="flex justify-center gap-10">
            <li>
              <Link href="/">home</Link>
            </li>
            <li>
              <Link href="/about">about</Link>
            </li>
            <li>
              <Link href="/report">report</Link>
            </li>
            <li>
              <Link href="/todos-csr">add todo</Link>
            </li>
            <li>
              <Link href="/todos-ssr">todo list</Link>
            </li>
          </ul>
        </nav>
        <QueryProvider>
          <div className="flex justify-center text-center bg-indigo-50">
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
